tap "buo/cask-upgrade"
tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Mac App Store command-line interface
brew "mas"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim", args: ["HEAD"]
# Platform built on V8 to build network applications
brew "node"
# Prompt theme engine for any shell
brew "oh-my-posh", args: ["HEAD"]
# General-purpose scripting language
brew "php"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Official tldr client written in Rust
brew "tlrc"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi", args: ["HEAD"]
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Real-time type-ahead completion for Zsh
brew "zsh-autocomplete"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# AeroSpace is an i3-like tiling window manager for macOS
cask "aerospace"
# Application launcher and productivity software
cask "alfred"
# Chromium based browser
cask "arc"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Tool to remove unnecessary files and folders from disk Chinese edition
cask "cleanmymac-zh"
cask "font-jetbrains-mono-nerd-font"
# Java IDE by JetBrains
cask "intellij-idea"
# Open-source keystroke visualiser
cask "keycastr"
# GPU-based terminal emulator
cask "kitty"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Spreadsheet software
cask "microsoft-excel"
# OpenJDK distribution from Microsoft
cask "microsoft-openjdk"
# Presentation software
cask "microsoft-powerpoint"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Word processor
cask "microsoft-word"
# Media player
cask "movist-pro"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Cloud storage manager tool
cask "piclist"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Mesh VPN based on WireGuard
cask "tailscale"
# Cloud video conferencing
cask "tencent-meeting"
# Unpacks archive files
cask "the-unarchiver"
# VPN client
cask "torguard"
# Video communication and virtual meeting platform
cask "zoom"
mas "GIPHY CAPTURE", id: 668208984
mas "Infuse", id: 1136220934
mas "iShot", id: 1485844094
