return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  lazy = false,
  main = "nvim-treesitter.configs",
  opts = {
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      "css",
      "dockerfile",
      "gitignore",
      "git_config",
      "html",
      "javascript",
      "json",
      "lua",
      "luadoc",
      "python",
      "query",
      "regex",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "markdown",
      "markdown_inline",
      "java",
      "cpp",
      "csv",
    },
  },
}
