return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  branch = "main",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    highlight = {
      enable = true,
      use_languagetree = true,
    },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      "css",
      "dockerfile",
      "gitignore",
      "git_config",
      "html",
      "javascript",
      "json",
      "latex",
      "lua",
      "luadoc",
      "python",
      "query",
      "regex",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "markdown",
      "markdown_inline",
      "java",
      "cpp",
      "csv",
    },
  },
}
