return {
  -- lspconfig, lualine
  DiagnosticError = "",
  DiagnosticHint = "󰌵",
  DiagnosticInfo = "󰋼",
  DiagnosticWarn = "",
  DapBreakpoint = "",
  DapBreakpointCondition = "",
  DapBreakpointRejected = "",
  DapLogPoint = ".>",
  DapStopped = "󰁕",
  -- lualine
  Lsp = "",
  CopilotEnabled = "",
  CopilotDsiabled = "",
  CopilotWarning = "",
  CopilotUnknown = "",
  Dot = "",
  Git = "",
  GitAdd = "",
  GitModified = "",
  GitRemoved = "",
  GitUnstaged = "✗",
  GitStaged = "✓",
  GitUnmerged = "",
  GitRenamed = "➜",
  GitUntracked = "",
  GitIgnored = "◌",
  GitConflict = "",
  -- which-key
  Buffer = "",
  Find = "",
  Manage = "",
  Java = "",
  Debug = "",
  Trouble = "󰌵",
  Terminal = "",
  -- nvim-tree
  Text = "",
  File = "󰈙",
  FileSymlink = "󱅷",
  BookMark = "",
  ChevronRight = "",
  ChevronShortDown = "",
  Folder = "󰉋 ",
  FolderOpen = " ",
  EmptyFolder = "",
  EmptyFolderOpen = "",
  FolderSymlink = "",
  Selected = "❯",
  Search = "",
  Command = "",
  Down = "",
  Up = "",
  Lua = "",
  Question = "",

  navic = {
    File = "󰈔 ",
    Module = "󰕳 ",
    Namespace = " ",
    Package = " ",
    Class = " ",
    Method = " ",
    Property = " ",
    Field = " ",
    Constructor = " ",
    Enum = " ",
    Interface = " ",
    Function = "󰡱 ",
    Variable = "󱄑 ",
    Constant = " ",
    String = " ",
    Number = " ",
    Boolean = " ",
    Array = "󰅨 ",
    Object = " ",
    Key = " ",
    Null = "󰟢 ",
    EnumMember = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
}
