return {
  -- lspconfig, lualine
  DiagnosticError = "",
  DiagnosticHint = "󰌵",
  DiagnosticInfo = "󰋼",
  DiagnosticWarn = "",
  DapBreakpoint = "",
  DapBreakpointCondition = "",
  DapBreakpointRejected = "",
  DapLogPoint = ".>",
  DapStopped = "󰁕",
  -- lualine
  Lsp = "",
  CopilotEnabled = "",
  CopilotDsiabled = "",
  CopilotWarning = "",
  CopilotUnknown = "",
  Git = "",
  GitAdd = "",
  -- which-key
  Buffer = "",
  Find = "",
  Manage = "",
  Java = "",
  Debug = "",
  Trouble = "󰌵",
  navic = {
    File = " ",
    Module = " ",
    Namespace = " ",
    Package = " ",
    Class = " ",
    Method = " ",
    Property = " ",
    Field = " ",
    Constructor = " ",
    Enum = " ",
    Interface = " ",
    Function = " ",
    Variable = " ",
    Constant = " ",
    String = " ",
    Number = " ",
    Boolean = " ",
    Array = " ",
    Object = " ",
    Key = " ",
    Null = " ",
    EnumMember = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
}
