return {
  dap = {
    DapBreakpoint = "",
    DapBreakpointCondition = "",
    DapBreakpointRejected = "",
    DapLogPoint = ".>",
    DapStopped = "󰁕",
  },
  lsp = {
    DiagnosticError = "",
    DiagnosticHint = "",
    DiagnosticInfo = "",
    DiagnosticWarn = "",
  },
  lualine = {
    CopilotEnabled = "",
    CopilotDsiabled = "",
    CopilotWarning = "",
    CopilotUnknown = "",
    DiagnosticError = "",
    DiagnosticHint = "",
    DiagnosticInfo = "",
    DiagnosticWarn = "",
    GitAdd = "",
    GitModified = "",
    GitRemoved = "",
    Lsp = "",
  },

  nvim_tree_glyphs = {
    default = "󰈔",
    symlink = "󱅷",
    folder = {
      default = "󰉋",
      empty = "󰉖",
      empty_open = "󰷏",
      open = "󰝰",
      symlink = "󱧬",
      symlink_open = "󱧭",
      arrow_open = "",
      arrow_closed = "",
    },
    git = {
      unstaged = "",
      staged = "",
      unmerged = "",
      renamed = "",
      untracked = "",
      deleted = "",
      ignored = "◌",
    },
  },
  telescope = {
    Selected = "",
    Search = "",
  },
  navic = { -- deprecated
    File = "󰈔 ",
    Module = "󰕳 ",
    Namespace = " ",
    Package = " ",
    Class = " ",
    Method = " ",
    Property = " ",
    Field = " ",
    Constructor = " ",
    Enum = " ",
    Interface = " ",
    Function = "󰡱 ",
    Variable = "󱄑 ",
    Constant = " ",
    String = " ",
    Number = " ",
    Boolean = " ",
    Array = "󰅨 ",
    Object = " ",
    Key = " ",
    Null = "󰟢 ",
    EnumMember = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
}
